<a href="https://colab.research.google.com/github/sherylsqin/CE888_2020/blob/master/Lab1/Lab_1_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import matplotlib.pyplot as plt
import numpy as np

In [4]:
#Create a (4 x 2) integer array and print it's attributes

int_array = np.array([[ 1, 2, 3, 4],
              [5,6,7,8]])

print("Array 4x2\n", int_array)

Array 4x2
 [[1 2 3 4]
 [5 6 7 8]]


In [14]:
#Create an array of dimension (1,10) and sort it in ascending and descending order

array10 = np.array([[7],[9],[3],[4],[1],[8],[5],[2],[6],[10]])

sorted_asc = np.sort(array10, axis=None)

sorted_des = np.sort(array10, axis=None)

print("Ascending Sort",sorted_asc)

print("Descending Sort",-np.sort(-sorted_des))

Ascending Sort [ 1  2  3  4  5  6  7  8  9 10]
Descending Sort [10  9  8  7  6  5  4  3  2  1]


In [16]:
#Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

first_array = [1,2,3,4,5,6,7,8,9]

array_2d = np.reshape(first_array,(-1,3))

print("2D Array",array_2d  )





2D Array [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
#Stack two arrays of any size horizontally and vertically


first_array = np.array([[1, 2], [3, 4]])

second_array = np.array([[5, 6]])

vertical_array = np.concatenate((first_array, second_array),axis=0)

horizontal_array = np.concatenate((first_array, second_array),axis=None)

print("Vertical",vertical_array)

print("Horizontal", horizontal_array)

Vertical [[1 2]
 [3 4]
 [5 6]]
Horizontal [1 2 3 4 5 6]


In [33]:
#Create two array of same size and find commom elements

first_array = np.array([[1, 2], [3, 5]])

second_array = np.array([[5, 1],[7, 8]])

common_element =np.intersect1d(first_array, second_array)

print("Common Element",common_element)



Common Element [1 5]


In [43]:
#Create a 2D array of 5 by 5 and find the min and max values from each row and each column

first_array = np.array([[1,6,12,4,99],[2,7,8,9,10],[3,8,9,14,32],[4,10,18,19,20],[5,11,23,24,25]])

print(first_array )

min_row = np.amin(first_array, axis=0)

print("\nMinimum of each row",min_row)

min_col = np.amin(first_array, axis=1)

print("\nMinimum of each column",min_col)

max_row = np.amax(first_array, axis=0)

print("\nMaximum of each row",max_row)

max_col = np.amax(first_array, axis=1)

print("\nMaximum of each column",max_col)


[[ 1  6 12  4 99]
 [ 2  7  8  9 10]
 [ 3  8  9 14 32]
 [ 4 10 18 19 20]
 [ 5 11 23 24 25]]

Minimum of each row [ 1  6  8  4 10]

Minimum of each column [1 2 3 4 5]

Maximum of each row [ 5 11 23 24 99]

Maximum of each column [99 10 32 20 25]


In [57]:
#Create an array of size 100 and compute the mean, median, standard deviation

rand_list = np.random.randint(200, size=(1,100))

print(rand_list)

mean = np.mean(rand_list)

print("\nMean", mean)

median = np.median(rand_list)

print("\nMedian",median)

std = np.std(rand_list)

print("\nStandard",std)



[[157  45  37  38  14  75  20  14 174 108 130 103  98  89 123 135 135  40
   10 148  87 134 168 164   1 177 193  27 170 130 144  99  72 115  96  36
    4  31  41  81  91  18 177  43 107  12  61 147  81 168  86 169 165 192
  163   2  54 162 161 138 157  82 167  55  40 197  29 164 114 130 164  36
   30   2 126  36 109  90  54 120  42  62  14  18  30 114 117  13  89  14
  100 175  91 162  43 104  80 107  12 179]]

Mean 93.28

Median 93.5

Standard 57.47626988592771


In [62]:
#Normalize a 5x5 random matrix

rand_list = np.random.randint(100, size=(5,5))

print(rand_list)

norm=np.linalg.norm(rand_list, ord=1)


print("\nNormalise",norm)

[[20 34 10 19  4]
 [63 94 49 22 47]
 [54 50 24 98 12]
 [28 94 54 55 89]
 [87 64 49 67 98]]

Normalise 336.0


In [73]:
#Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)

rand_1 = np.random.randint(5, size=(4,4,3))

print("\nMatrix 4 x 4 x 3\n",rand_1)

rand_2 = np.random.randint(5, size=(4,4))

print("\nMatrix 4 x 4\n",rand_2)

multi = np.dot(rand_2,rand_1)

print("\nMultiply\n",multi)



Matrix 4 x 4 x 3
 [[[4 4 4]
  [4 3 1]
  [0 3 4]
  [4 4 2]]

 [[0 4 1]
  [3 0 0]
  [0 1 3]
  [0 3 3]]

 [[4 0 1]
  [0 1 1]
  [4 1 2]
  [0 4 0]]

 [[0 1 0]
  [4 0 0]
  [1 1 4]
  [1 4 1]]]

Matrix 4 x 4
 [[2 2 4 0]
 [3 3 2 3]
 [3 1 1 2]
 [2 0 0 0]]

Multiply
 [[[16 26 26]
  [ 6 12 14]
  [24  6 12]
  [12  6 16]]

 [[36 39 29]
  [ 9 23 18]
  [20 17 10]
  [17 17 11]]

 [[24 26 21]
  [ 3 19 12]
  [16 10  6]
  [ 7 12  6]]

 [[ 8  8  8]
  [ 0  8  2]
  [ 8  0  2]
  [ 0  2  0]]]
